- Readme.md
Installation instructions are a bit confusing, I edited the instruction to be more clear for everyone.
> Updated installation instructions in readme.md

- Readme.md
Install aerial easily with using ```brew cask install aerial```
> Install with Homebrew Cask

- Readme.md
> Fixed typo in Readme file :)

- Readme.md
fixed link to John's personal twitter account
> update personal twitter link

- issue_template.md
Attempting to reduce the number of duplicate issues. :)
> Adding issue template

- Aerial.xcodeproj/project.pbxproj
- Aerial/App/AppDelegate.swift
- Aerial/App/Resources/Info.plist
- Aerial/Resources/Info.plist
- Aerial/Resources/PreferencesWindow.xib
- Aerial/Source/Controllers/Preferences.swift
- Aerial/Source/Controllers/PreferencesWindowController.swift
- Aerial/Source/Models/AerialVideo.swift
- Aerial/Source/Models/Cache/VideoCache.swift
- Aerial/Source/Models/Cache/VideoDownload.swift
- Aerial/Source/Models/Cache/VideoLoader.swift
- Aerial/Source/Models/Extensions/CollectionType+Shuffling.swift
- Aerial/Source/Models/ManifestLoader.swift
- Aerial/Source/Views/AerialPlayerItem.swift
- Aerial/Source/Views/AerialView.swift
- Aerial/Source/Views/CheckCellView.swift
- Readme.md
- issue_template.md
This is a followup to this PR https://github.com/JohnCoates/Aerial/pull/500 (originally based on @esetnik Feature/4k branch) with some extra changes/features : 
- updated to Swift 4.2/Xcode 10
- switch (in cache panel) for 1080p/4K
- Video description now shown (by default, configurable) bottom left of the screen for 10 seconds 
- added a version number at the bottom right of the panel
> tvOS12 1080p + 4K, Swift 4.2, Video descriptions, fix Done button

- Readme.md
Expanded readme for 1.4, with extra sections regarding offline usage, hardware decoding, and new features. 
Still need fresh screenshots :)
> Update readme for 1.4

- Aerial/Resources/Info.plist
- Aerial/Source/Views/AerialView.swift
> More multimonitor mode fix, retested all cases, should be safer now 1.2.4b4

- Aerial/Resources/Info.plist
- Aerial/Source/Models/Cache/VideoCache.swift
- Aerial/Source/Models/Cache/VideoDownload.swift
- Aerial/Source/Models/Cache/VideoManager.swift
> Clean up some retain cycles in VideoCache and VideoDownload

- .swiftlint.yml
- .travis.yml
- Aerial.xcodeproj/project.pbxproj
- Aerial/App/AppDelegate.swift
- Aerial/Source/Controllers/Preferences.swift
- Aerial/Source/Controllers/PreferencesWindowController.swift
- Aerial/Source/Models/AerialVideo.swift
- Aerial/Source/Models/Cache/AssetLoaderDelegate.swift
- Aerial/Source/Models/Cache/PoiStringProvider.swift
- Aerial/Source/Models/Cache/VideoCache.swift
- Aerial/Source/Models/Cache/VideoDownload.swift
- Aerial/Source/Models/Cache/VideoLoader.swift
- Aerial/Source/Models/Cache/VideoManager.swift
- Aerial/Source/Models/Downloads/AsynchronousOperation.swift
- Aerial/Source/Models/Downloads/DownloadManager.swift
- Aerial/Source/Models/ErrorLog.swift
- Aerial/Source/Models/Extensions/AVPlayerViewExtension.swift
- Aerial/Source/Models/Extensions/CollectionType+Shuffling.swift
- Aerial/Source/Models/ManifestLoader.swift
- Aerial/Source/Models/Time/Solar.swift
- Aerial/Source/Models/Time/TimeManagement.swift
- Aerial/Source/Views/AerialPlayerItem.swift
- Aerial/Source/Views/AerialView.swift
- Aerial/Source/Views/CheckCellView.swift
- Makefile
- Tests/PreferencesTests.swift
- Added a Makefile for easier scripting
- Fixed the project setting to use Swift 4.2 correctly
- Added a run script to run Swiftlint
- Auto corrected and manually fixed most swiftlint warnings (added exceptions where the work was too risky)
- Updated CI to run new Makefile `test` and `lint` steps.
> Adding a Makefile and fixing Swiftlint

- Readme.md
I am going to test before I change it again:)'
Edit: Brew is updated for 1.4.5:)
Also can you fix Travis?
> Brew Cask Update????

- Aerial/Source/Controllers/PreferencesWindowController.swift
Uses case let in switch statements where appropriate in PreferencesWindowController.swift
> Uses case let in switch statement

- Aerial/Source/Controllers/Preferences.swift
- Aerial/Source/Controllers/PreferencesWindowController.swift
> Revert "Removes not needed synchronize method"

- Aerial/Source/Models/AerialVideo.swift
- Aerial/Source/Models/ManifestLoader.swift
- Resources/Community/en.json
- Resources/Community/missingvideos.json
- Resources/Info.plist
- Resources/PreferencesWindow.xib
> Fix for 10.9 label length, december batch of videos

- Aerial/Source/Controllers/PreferencesWindowController.swift
- Aerial/Source/Models/ManifestLoader.swift
- Aerial/Source/Views/CheckCellView.swift
- Resources/Info.plist
- Resources/PreferencesWindow.xib
> Move old videos/trash old videos, check now button, 1.4.6 finale

- Aerial.xcodeproj/project.pbxproj
- Aerial/App/Resources/Info.plist
- Aerial/Source/Controllers/PreferencesWindowController.swift
- Aerial/Source/Models/AerialVideo.swift
- Aerial/Source/Models/Cache/VideoCache.swift
- Aerial/Source/Models/ErrorLog.swift
- Aerial/Source/Models/ManifestLoader.swift
- Aerial/Source/Views/AerialView.swift
- Podfile
- Podfile.lock
- Resources/Community/en.json
- Resources/Community/missingvideos.json
- Resources/Info.plist
- Resources/PreferencesWindow.xib
1.4.7 beta, new videos from jan 25th, sparkle for auto updates, bug fix for missing cache folder, new Update pane interface (in progress)
> update main repo to 1.4.7beta2 

- Resources/Community/es.json
Hi there,
I've localized the community info to spanish. @glouel let me know if you need any other resource translated.
> Spanish Localization

- Resources/Community/es.json
cf. https://github.com/JohnCoates/Aerial/pull/713#issuecomment-45976065
> Some more space videos added to the community file (spanish)

- Readme.md
- Resources/Community/Readme.md
- New Multilanguage support section added to the main Readme. 
- Lokalise sponsorship added to the translation Readme.
> Multilanguage support docs

- Resources/Community/pl.json
> Polish translation.

- Resources/Community/Readme.md
Sorry, there were some typos on the links
> Fix the hrefs of the referenced users

- Resources/Community/Readme.md
- Resources/Community/de.json
> German translations. Ich bin überglücklich!

- Aerial.xcodeproj/project.pbxproj
- Aerial.xcodeproj/xcshareddata/xcschemes/Aerial.xcscheme
- Aerial/Source/Controllers/Preferences.swift
- Aerial/Source/Controllers/PreferencesWindowController.swift
- Aerial/Source/Models/Cache/PoiStringProvider.swift
- Aerial/Source/Views/AerialView.swift
- Resources/Info.plist
- Resources/PreferencesWindow.xib
Allow to pick a translation in settings
Beta 8
> Add Arabic language support

- Aerial/Source/Controllers/PreferencesWindowController.swift
- Resources/Info.plist
> Add time to the update check

- Aerial/Source/Views/AerialView.swift
- Resources/Info.plist
> Switch to nextResponder forwarding, just in case it fixes an issue

- Readme.md
Set mockup `to center`. I am attach screenshoots:
> Update Readme: Set mockup to center

- Aerial.xcodeproj/project.pbxproj
- Aerial/App/Resources/Info.plist
- Aerial/Source/Controllers/PWC Tabs/PWC+Advanced.swift
- Aerial/Source/Controllers/PWC Tabs/PWC+Brightness.swift
- Aerial/Source/Controllers/PWC Tabs/PWC+Cache.swift
- Aerial/Source/Controllers/PWC Tabs/PWC+Displays.swift
- Aerial/Source/Controllers/PWC Tabs/PWC+Text.swift
- Aerial/Source/Controllers/PWC Tabs/PWC+Time.swift
- Aerial/Source/Controllers/PWC Tabs/PWC+Updates.swift
- Aerial/Source/Controllers/PWC Tabs/PWC+Videos.swift
- Aerial/Source/Controllers/PWC+LogPanel.swift
- Aerial/Source/Controllers/PreferencesWindowController.swift
- Aerial/Source/Models/CustomVideoFolders+helpers.swift
- Aerial/Source/Models/HardwareDetection.swift
- Resources/Info.plist
Still a WIP but will make it easier to maintain
> Cleanup of PreferenceViewController

- Aerial.xcodeproj/project.pbxproj
- Aerial/Source/Controllers/PWC Tabs/PWC+Advanced.swift
- Aerial/Source/Controllers/PWC Tabs/PWC+Brightness.swift
- Aerial/Source/Controllers/PWC Tabs/PWC+Videos.swift
- Aerial/Source/Controllers/Preferences.swift
- Aerial/Source/Controllers/PreferencesWindowController.swift
- Aerial/Source/Models/AerialVideo.swift
- Aerial/Source/Models/DisplayDetection.swift
- Aerial/Source/Models/ManifestLoader.swift
- Resources/PreferencesWindow.xib
> 1.5.1beta3 with HDR support (Catalina Only)

- Aerial.xcodeproj/project.pbxproj
- Aerial/Source/Controllers/PWC Tabs/PWC+Videos.swift
- Aerial/Source/Controllers/Preferences.swift
- Aerial/Source/Models/DisplayDetection.swift
> Disable video format choice on < 10.13

- Aerial/Source/Controllers/PWC Tabs/PWC+Cache.swift
- Aerial/Source/Controllers/PreferencesWindowController.swift
- Aerial/Source/Models/Cache/PoiStringProvider.swift
- Aerial/Source/Models/Cache/VideoCache.swift
- Resources/PreferencesWindow.xib
Fix POI no longer loading in beta 5/6
Aerial will now use ~/Library/Application Support/Aerial as it's default cache for new users
beta 7
> Add workaround message box to change cache folder in Catalina

- Aerial.xcodeproj/project.pbxproj
- Aerial/Source/Controllers/PWC Tabs/PWC+Cache.swift
- Aerial/Source/Models/ManifestLoader.swift
> Fix false customvideos.json error message

- Aerial.xcodeproj/project.pbxproj
- Aerial.xcodeproj/xcshareddata/xcschemes/Aerial.xcscheme
- Aerial/Source/Models/AerialVideo.swift
- Aerial/Source/Models/AutoUpdates.swift
- Aerial/Source/Models/BatteryManagement.swift
- Aerial/Source/Models/ManifestLoader.swift
- Aerial/Source/Models/Time/TimeManagement.swift
- Aerial/Source/Views/AerialView+Brightness.swift
- Aerial/Source/Views/AerialView.swift
> Bit of cleanup

- Readme.md
In the community section added a link to a webpage that lists all the available videos.
For people that want to see the videos first.
> Updated README. 

- Readme.md
Minor updates to ReadMe 
- Typos
- Clarified wording
> ReadMe Minor Updates

- Aerial.xcodeproj/project.pbxproj
This allows building from the command line without further ado.
> Add missing dependency to Xcode project.

- Resources/MainUI/First time setup/WelcomeViewController.xib
"set up" is the verb and "setup" is the noun :)
Happy new year 🥳
> Welcome view: Grammar

- Resources/MainUI/Infos panels/CreditsViewController.xib
- Resources/MainUI/Infos panels/HelpViewController.xib
- Resources/MainUI/Infos panels/InfoViewController.xib
- Resources/MainUI/Settings panels/AdvancedViewController.xib
- Resources/MainUI/Settings panels/BrightnessViewController.xib
- Resources/MainUI/Settings panels/CompanionCacheViewController.xib
- Resources/MainUI/Settings panels/DisplaysViewController.xib
- Resources/MainUI/Settings panels/FiltersViewController.xib
- Resources/MainUI/Settings panels/NowPlayingViewController.xib
- Resources/MainUI/Settings panels/OverlaysViewController.xib
- Resources/MainUI/Settings panels/SourcesViewController.xib
- Resources/MainUI/Settings panels/TimeViewController.xib
- Resources/MainUI/VideosViewController.xib
This pull request adds constraints to ensure that windows are fixed to or at least 811x530 and some other minor fixes.
> Fix window constraints
